RPKINullScheme2025
  { iso(1) member-body(2) us(840) rsadsi(113549)
    pkcs(1) pkcs-9(9) smime(16) modules(0) null-scheme-2025(TBD) }
-- TODO: module ID to be replaced by IANA

DEFINITIONS IMPLICIT TAGS ::= BEGIN

EXPORTS ALL;

IMPORTS
  PUBLIC-KEY, SIGNATURE-ALGORITHM
    FROM AlgorithmInformation-2009  -- RFC 5912
      { iso(1) i id-mod(0)
        id-mod-algorithmInformation-02(58) }
;

-- TODO: OIDs to be replaced by IANA
id-RPKI-NULL-SCHEME-SHA256 OBJECT IDENTIFIER ::= {
    dentified-organization(3) dod(6) internet(1)
        security(5) mechanisms(5) pkix(7) alg(6) TBD
  }

pk-RPKI-NULL-SCHEME-SHA256 PUBLIC-KEY ::= {
    IDENTIFIER id-RPKI-NULL-SCHEME-SHA256
    -- We opted to use an OID for the Null Scheme *with SHA256*.
    -- Alternatively, there could be a Null Scheme OID, with a required digest algorithm param.
    PARAMS ARE absent
    -- A Null Scheme public key should only be certified by EE certificates.
    -- So, in accordance with RFC6487, only the digitalSignature bit is valid.
    CERT-KEY-USAGE {digitalSignature} 
  }

sa-RPKI-NULL-SCHEME-SHA256 SIGNATURE-ALGORITHM ::= {
    IDENTIFIER id-RPKI-NULL-SCHEME-SHA256
    PARAMS ARE absent
    PUBLIC-KEYS {pk-RPKI-NULL-SCHEME-SHA256}
  }

END